"""Shared converter interfaces for Digital Polymerase.

The converter layer is the semi-stable user-facing layer above
``digital_polymerase.core``.

Prototype scripts are allowed to be experimental and target-specific.
Converters should be cleaner wrappers that:

- accept explicit input/output paths
- avoid hardcoded local paths
- call reusable core modules
- write standard PDB/report/metrics outputs
- fail with clear errors
- remain honest about computational-candidate status

This module intentionally contains only lightweight dataclasses and helpers.
Actual reconstruction logic belongs in target-specific converter modules such as
``rna_to_fana.py``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal


ConverterStatus = Literal[
    "success",
    "partial",
    "failed",
    "not_run",
]


@dataclass(frozen=True)
class ConverterConfig:
    """Configuration shared by stable/semi-stable converter wrappers.

    Attributes:
        target:
            Target nucleic-acid/XNA family, for example ``"FANA"``.
        strategy:
            Reconstruction strategy name, for example ``"chain_preserving"``.
        strict:
            If True, raise errors for validation failures instead of only
            reporting them.
        write_json:
            If True, write machine-readable JSON metrics when a metrics path is
            provided.
        write_pymol_script:
            Reserved for future visualization helper output.
        notes:
            Optional free-text notes that can be inserted into reports.
    """

    target: str
    strategy: str
    strict: bool = False
    write_json: bool = True
    write_pymol_script: bool = False
    notes: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class ConverterPaths:
    """Input/output paths used by a converter run.

    Attributes:
        input_pdb:
            Source nucleic-acid PDB.
        template_pdb:
            Target XNA template PDB, if required by the strategy.
        output_pdb:
            Candidate output PDB.
        report_md:
            Human-readable Markdown report.
        metrics_json:
            Optional machine-readable metrics JSON.
    """

    input_pdb: Path
    output_pdb: Path
    report_md: Path
    template_pdb: Path | None = None
    metrics_json: Path | None = None

    @classmethod
    def from_strings(
        cls,
        *,
        input_pdb: str | Path,
        output_pdb: str | Path,
        report_md: str | Path,
        template_pdb: str | Path | None = None,
        metrics_json: str | Path | None = None,
    ) -> "ConverterPaths":
        """Build ``ConverterPaths`` from strings or ``Path`` objects."""
        return cls(
            input_pdb=Path(input_pdb),
            template_pdb=Path(template_pdb) if template_pdb is not None else None,
            output_pdb=Path(output_pdb),
            report_md=Path(report_md),
            metrics_json=Path(metrics_json) if metrics_json is not None else None,
        )


@dataclass
class ConversionResult:
    """Standard return object for converter functions.

    Attributes:
        target:
            Target nucleic-acid/XNA family.
        strategy:
            Strategy used for reconstruction.
        status:
            Run status: ``success``, ``partial``, ``failed``, or ``not_run``.
        sequence:
            Source sequence extracted or used by the converter.
        residue_count:
            Number of converted residues.
        paths:
            Input/output path bundle.
        validation:
            Validation result dictionary, ideally generated by
            ``digital_polymerase.core.validation``.
        messages:
            Human-readable notes, warnings, or errors.
        metadata:
            Optional converter-specific data.
    """

    target: str
    strategy: str
    status: ConverterStatus
    sequence: str
    residue_count: int
    paths: ConverterPaths
    validation: dict[str, Any] = field(default_factory=dict)
    messages: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        """Return True for fully successful conversion."""
        return self.status == "success"

    @property
    def has_warnings(self) -> bool:
        """Return True when result contains messages."""
        return bool(self.messages)


def ensure_output_dirs(paths: ConverterPaths) -> None:
    """Create parent folders for converter outputs."""
    paths.output_pdb.parent.mkdir(parents=True, exist_ok=True)
    paths.report_md.parent.mkdir(parents=True, exist_ok=True)
    if paths.metrics_json is not None:
        paths.metrics_json.parent.mkdir(parents=True, exist_ok=True)


def summarize_result(result: ConversionResult) -> str:
    """Return a compact human-readable result summary."""
    return (
        f"{result.target} conversion using {result.strategy}: "
        f"{result.status} ({result.residue_count} residues)"
    )
